image: node:18

variables:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

stages:
  - test

test:
  stage: test
  script:
    # Install dependencies
    - npm ci
    - npm install -g playwright
    - npx playwright install --with-deps
    
    # Start the HTTP server and wait for it to be ready
    - npx http-server src -p 8080 &
    - sleep 5
    
    # Run Playwright tests
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 1 week