name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and dependencies
        run: |
          npm install -g playwright serve
          npx playwright install --with-deps

      - name: Check src/ folder contents
        run: ls -la src/

      - name: Start HTTP server
        run: |
          serve -s src -l 8080 & 
          sleep 5
          curl --retry 10 --retry-connrefused --retry-delay 3 http://localhost:8080

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/